### ISSUE TITLE
Sub-task for raw table extracts

### ISSUE THREAD

**Issue by emdeh** [emdeh/pdf-document-processor#66]

**Comment by emdeh** [comment]
- Created a new processing script called `raw_process.py`
- Created a new method in the `DocAIUtils` class called `extract_all_text`
- Created a new method in the `CSVUtils` class called `write_raw_data_to_excel`
- Created a new "empty" `statement_type` in the `type_models.yaml`:
```yaml
  - type_name: "Raw-extract"
    env_var: "PRE_BUILT_READ"
    summary_fields: []
    transaction_static_fields: []
    transaction_dynamic_fields: []
```
- Called the pre-built read model from Microsoft `PRE_BUILT_READ=prebuilt-read` within the `.env`

This extracts all data and writes it all into a single cell for further processing by existing tools. Currently being tested by business.
